version: '3.8'
services: 
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: app-container
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${DB_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    ports: 
      - "8000:8000" 
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules